# admin
admin1 = Admin.create!({name: "admin1", email: "admin1@test.com", password: "password", password_confirmation: "password"})
admin2 = Admin.create!({name: "admin2", email: "admin2@test.com", password: "password", password_confirmation: "password"})
admin3 = Admin.create!({name: "admin3", email: "admin3@test.com", password: "password", password_confirmation: "password"})
# user
user1 = User.create({name: "user1", email: "user1@test.email", password: "password", password_confirmation: "password"})
user2 = User.create({name: "user2", email: "user2@test.email", password: "password", password_confirmation: "password"})
user3 = User.create({name: "user3", email: "user3@test.email", password: "password", password_confirmation: "password"})
# project
project1 = Project.create({title: "title1", admin_id: 1})
project2 = Project.create({title: "title2", admin_id: 2})
project3 = Project.create({title: "title2", admin_id: 3})
# subject
subject1 = Subject.create({title: "title1", project_id: 1})
subject2 = Subject.create({title: "title2", project_id: 1})
subject3 = Subject.create({title: "title3", project_id: 1})
subject1 = Subject.create({title: "title1", project_id: 2})
subject2 = Subject.create({title: "title2", project_id: 2})
subject3 = Subject.create({title: "title3", project_id: 2})
subject1 = Subject.create({title: "title1", project_id: 3})
subject2 = Subject.create({title: "title2", project_id: 3})
subject3 = Subject.create({title: "title3", project_id: 3})
subject4 = Subject.create({title: "title4", project_id: 1})
subject5 = Subject.create({title: "title5", project_id: 1})
subject6 = Subject.create({title: "title6", project_id: 1})
subject4 = Subject.create({title: "title4", project_id: 2})
subject5 = Subject.create({title: "title5", project_id: 2})
subject6 = Subject.create({title: "title6", project_id: 2})
subject4 = Subject.create({title: "title4", project_id: 3})
subject5 = Subject.create({title: "title5", project_id: 3})
subject6 = Subject.create({title: "title6", project_id: 3})
# subject1part
part1 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part2 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part3 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part4 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part5 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part6 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part7 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part8 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part9 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
part10 = Part.create({title: "title1", content: "content1", subject_id: 1, status: 0})
# subject2part
part1 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part2 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part3 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part4 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part5 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part6 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part7 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part8 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part9 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
part10 = Part.create({title: "title1", content: "content1", subject_id: 2, status: 0})
# subject3part
part1 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part2 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part3 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part4 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part5 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part6 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part7 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part8 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part9 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
part10 = Part.create({title: "title1", content: "content1", subject_id: 3, status: 0})
# user3question
question1 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question2 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question3 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question4 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question5 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question6 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question7 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question8 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question9 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
question10 = Question.create({title: "title1", content: "content1", user_id: 3, part_id: 1, subject_id: 1, project_id: 1})
# user2question
question1 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question2 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question3 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question4 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question5 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question6 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question7 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question8 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question9 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
question10 = Question.create({title: "title1", content: "content1", user_id: 2, part_id: 1, subject_id: 1, project_id: 1})
# user1question
question1 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question2 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question3 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question4 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question5 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question6 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question7 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question8 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question9 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
question10 = Question.create({title: "title1", content: "content1", user_id: 1, part_id: 1, subject_id: 1, project_id: 1})
# project_admin
project_admin1 = ProjectAdmin.create({admin_id: 1, project_id: 1})
project_admin1 = ProjectAdmin.create({admin_id: 2, project_id: 2})
project_admin1 = ProjectAdmin.create({admin_id: 3, project_id: 3})
# project_user
project_user1 = ProjectUser.create({user_id: 1, project_id: 1})
project_user1 = ProjectUser.create({user_id: 2, project_id: 2})
project_user1 = ProjectUser.create({user_id: 3, project_id: 3})
